spring:
  application:
    name: Shop
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_g33
    username: postgres
    password: Kaktus2024
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: Tmu6OXdunqE7e4tVVWrJF3OdlxuJGcmvZt8yjSJqNXU=
  refresh: BMpbW0LGCu9wEjeRCiomM6tIvHFncb4kplb4yfHELCU=


messages:
  hello: Hello from local application!
